[google_credentials]
type = "service_account"
project_id = "food-recipe-warehouse"
private_key_id = "15f86e2d8d6bcb7efdd5701c0eaf08fd78dbfca8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDtnGe26E4Kd5lp
/YUsYE4WKfbw4xKWdEkOevz3WfWb1zXbfNmAzGO/FGwHUNHWjw31fGtEz8MLft7G
vT5eCt0N9v3SBJtvBBc4+m/lLvENlpT+I6Jf7QPP1Hcm/p4E5jA3ozkFU2m2AdWR
tpnPhvGRGr4WwvExyNEc3iORMNLzNa8a7+RbTwJFa6HD2Q/5yd1ZHx49siwHHiTe
4vllEUsyBcB24zE8M4tuOha9EBpfChAwa2TVajdNe+bZXPEh9LPxet/hrjqhtusK
pQTI+vp2HvL2EERUs6hC7gPqBHORZ8Nx7ueBnC9Et224GF2OtbI5tpebdt1xIxc4
1BhmfBMxAgMBAAECggEAG+Firoy4zoPc05nYqN22f+WF6Rs91LtZkKpH+TacKgBx
PHs8cr9Y02SQLfYS3yoLPWMvW4RE2roU5g0xzptX95HkE8LwYZEBcBE7tLDCvmFN
Q3o3LOoMzNO9dO0CqejAHuEnOUuhr2Zs8sNyLg6DlQ8GH7nZTwoFFm3uzrQjxn9r
1dj9Ha2tfYRwxNhy1h/oP02OOZ6REoI0vmfZp3U+lMHfNLxjahXa552fehu+rt4K
xzlq8l1E1W69Kx/uGqE4vDFu2OOnRHwPMUt2XUaosDlhpG4zG3Lgs4N7/oTVLd57
u/LHFZaiwFgc5NdBAQalKry4ivYmVXBT6mkUYrgDmQKBgQD5bd4LAFPskjORkjYy
aiWwZJGv5uQ9T3CfjykKZdDPcpbXhvQJeU2HF5o+w03Z5rn5DYNSlHxZO531Z0B6
RhJgTLU3MJj+PC3SgAkqMGEfN2XU+3EU060/Ww616pDoaki6B+vayIF4EzbTt3SI
iK1am6ErDDVgKVIcobcYSnLWqQKBgQDz3tYrLY3ulvY4wdfw8Brgk14Jbw8xM0jb
wlFHVfGc17ly2RXfEXN13TzlnwbCGXxQ772kGB26ff3/oc4Ot0DwUe1cWIe2cYR+
8ZzkoSGEOjsRJLgCvn4J2SfmCRyB2HZ5njHFmSAp96CLUqrFIWi5chXuRSLpF9bc
B6xBoLkVSQKBgAUYnI/G+u/7cLhJr3fKOWjoNR3N7t3d0KRB7Ym72M9UPQa8SCIl
a1MWRV2A6gdIsoYHI6a9R+ke0bRg3q1g3yE+j/lHseiH3DvPx+AnyuQzYo4+cOoH
BSQlPSC0YS+OdFvwq3312MdWRSmANw5PFJOkWF+jyTdkwLu7Bh2l78C5AoGBAL+O
K8AiujfM0H7olEwm7ZW1a8oROGe3FuW3jsxvz6cZNAvoROvA82aDb1AWR+Kyzhlt
FxML9l4ElTz0xbx9aT7bu4wr5f4C0MY91rUndAI/EyJ2KyvMoYfu0Q453fCILRd+
kS3bB46veaW2O3k4st/nox5TpAZfuV9/j2jFbFwxAoGBAL6FdPebVY6ohspk7+dM
GQrw0VshAQMuHE7lt1rpcSpY1D9HvV04rxBrtosA7LNyt0Te8O0aXBQvjnTuvd9E
c6/eIiLuaC1I+V5hemeQ56MFmxCVT8Le5YxCQmysVCPLXxiz09mjuCmr4/DlVw4f
eJMewdOKPalNdEf3Z/d7no/q
-----END PRIVATE KEY-----
"""
client_email = "food-recipe-creds@food-recipe-warehouse.iam.gserviceaccount.com"
client_id = "107574226628998113438"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/food-recipe-creds%40food-recipe-warehouse.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
